### ISSUE TITLE
Detect python version from common files

### ISSUE THREAD

**Issue by EmilStenstrom** [strokirk/pyenv-autoenv#2]
Suggestion: If running without the --version command, try detecting the version from some common files:

* pyproject.toml - There's a field there that could be set
* runtime.txt - Is set to i.e. python-3.9.1 in all Heroku/Dokku setups
* setup.py - For libraries
* more?

I think this fits with the "automatic environment setup" idea nicely! :)

**Comment by strokirk** [comment]
I think these are great suggestions! 

I tried to do automatic detection via `pyproject.toml`, but unfortunately couldn't find a good way to parse the `toml` syntax. I guess we can simply grep for `^\s*requires-python\s*=\s*(.*)$`, but I'm a little worried about the wrong version being picked up or formatting edge cases being missed.

**Comment by Frost** [comment]
Maybe try to grep for something like that regex but then also prompt the user to ask if that's the correct version? The "automatic" setup idea is really nice, but sometimes, if a tool makes an incorrect guess I would rather have it ask me to confirm before going ahead and installing the wrong thing (like in #1, for instance).

**Comment by EmilStenstrom** [comment]
I'm not that worried about strange syntax. 99% of toml files are SUPER simple, and if the last percentage gives someone problems and they post it as an issue here it will be easy to solve with a concrete use-case to look at. 

My bash-foo isn't great, so I would just pick any of these examples: https://stackoverflow.com/questions/61084701/parse-just-a-tiny-part-of-toml-with-sed-or-grep-with-a-multiline-regex

For runtime.txt it should be just cutting the "python-" prefix and using that version.

For setup.py there's a python_requires-key that specifies a version. I would regex-grep it the same way as with pyproject.toml. Might take a little trickery because this can be prefixed with ">" (at least, should pick the latest version of python?), and "<" (at most, should pick that version).

**Comment by EmilStenstrom** [comment]
I'm fine with aborting a command with ^C if it picks the incorrect version, so no need for a prompt for my sake. Installation takes at least a minute, so there's lots of time to abort. If you add a prompt this tool gets harder to use from the command line, since you need to pipe input into it.

**Comment by EmilStenstrom** [comment]
Works great! Would you be open to adding support for setup.py too? Here's an example: https://github.com/EmilStenstrom/conllu/blob/master/setup.py#L10

**Comment by strokirk** [comment]
Yes, definitely open to supporting setup.py! I think `setup.cfg` should be supported as well, in that case. (Same caveats as the other formats apply.)

**Comment by strokirk** [comment]
@EmilStenstrom Support for `setup.py` files should now be added to the latest version of `pyenv autoenv`. Thanks for the suggestion!

**Comment by EmilStenstrom** [comment]
Awesome! 😎
